service: ua-aws-handler-2020

frameworkVersion: ">=1.2.0 <2.0.0"

provider:
  name: aws
  runtime: python2.7 # or python3.7, supported as of November 2018
  iamRoleStatements: # permissions for all of your functions can be set here
    - Effect: Allow
      Action: # Gives permission to DynamoDB tables in a specific region
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
        - s3:ListBucket
        - s3:PutObject
        - s3:GetObject
        - s3:DeleteObject
      Resource: '*'

functions:
  mys3trigger:
    handler: handler.endpoint
    events:
      - s3: ua-s3-storage-2020
resources:
  Resources: 
    usersTable: 
      Type: "AWS::DynamoDB::Table"
      Properties: 
        AttributeDefinitions: 
          - 
            AttributeName: "sample_id"
            AttributeType: "S"
          - 
            AttributeName: "test_type"
            AttributeType: "S"
        KeySchema: 
          - 
            AttributeName: "sample_id"
            KeyType: "HASH"
          - 
            AttributeName: "test_type"
            KeyType: "RANGE"
        ProvisionedThroughput: 
          ReadCapacityUnits: "5"
          WriteCapacityUnits: "5"
        TableName: "ua-dynamodb-storage-2020"